-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u2
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Jeu 28 Mars 2019 à 14:09
-- Version du serveur: 5.5.47
-- Version de PHP: 5.4.45-0+deb7u2

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `ocde`
--

-- --------------------------------------------------------

--
-- Structure de la table `indicators_new3`
--

CREATE TABLE IF NOT EXISTS `indicators_new3` (
  `id` int(5) NOT NULL,
  `name` varchar(255) NOT NULL,
  `dataviz_type` varchar(255) NOT NULL,
  `direction` tinyint(1) NOT NULL DEFAULT '0',
  `key_indicator` tinyint(1) NOT NULL DEFAULT '0',
  `family` varchar(255) NOT NULL,
  `classif` varchar(255) NOT NULL,
  `area` varchar(255) NOT NULL,
  `level` varchar(255) NOT NULL,
  `final_list` tinyint(1) NOT NULL DEFAULT '0',
  `note` text NOT NULL,
  `source` text NOT NULL,
  `definition` text NOT NULL,
  `tag` varchar(255) NOT NULL,
  `timeseries` int(1) NOT NULL,
  `default_cpage` varchar(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `indicators_new3`
--

INSERT INTO `indicators_new3` (`id`, `name`, `dataviz_type`, `direction`, `key_indicator`, `family`, `classif`, `area`, `level`, `final_list`, `note`, `source`, `definition`, `tag`, `timeseries`, `default_cpage`) VALUES
(1, 'Access to water', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on access to water, according to international standards. Access to an improved water source is currently defined as the percentage of the population that can obtain at least 20 liters per person per day from an “improved” source that is within one kilometer of the user’s dwelling. Improved water sources include household connection, public standpipe, borehole, protected well or spring, and rainwater collection, but do not include water provided through vendors, tanker trucks, unprotected wells, unprotected springs, and bottled water. Unsafe water and lack of basic sanitation is the direct cause of many water-related diseases in developing countries. This indicator monitors access to improved water sources based on the assumption that improved sources are likely to provide safer water and relates to the seventh MDG to ensure environmental sustainability.', 'indicator (0 or 1)', 1, ''),
(2, 'Accessible microdata', 'bar graph', 1, 0, 'Statistical production processes', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'Accessibility of micro data sets online. ', 'quantity', 0, ''),
(3, 'Outreach to users ', 'binary', 1, 0, 'Relationship with users', 'Dissemination', 'Politics and Power', 'System', 1, '', 'PARIS21', 'Whether the NSO has an active outreach to users.', 'indicator (0 or 1)', 0, ''),
(4, 'Advocacy material', 'binary', 1, 0, 'Advocacy strategy', 'Dissemination', 'Management', 'System', 0, '', 'PARIS21', 'Existence of booklet or material used by  country for advocacy for statistics at national level', '', 0, ''),
(5, 'Agricultural census', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of an agricultural census, according to international standards. Agricultural censuses collect information on agricultural activities, such as agricultural land use, employment and production, and provide basic structural data and sampling frames for agricultural surveys. It is recommended that agricultural censuses be conducted at least every 10 years.', 'indicator (0 or 1)', 1, ''),
(6, 'Available microdata ', 'bar graph', 1, 0, 'Existing data', 'Dissemination', 'Resources', 'System', 1, '', 'PARIS21', 'Availability of microdata datasets.', 'quantity', 0, ''),
(7, 'Balance of payments manual in use', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Usage of a balance of payments manual, according to international standards. The Balance of Payments Manual serves as an international standard for the compilation of balance of payments statistics. The manual has evolved to meet changing economic and financial environment and analytic requirements. The first edition was published in 1948 and successive editions in 1950, 1961, 1977, 1993, and 2013.', 'indicator (0 to 1)', 1, ''),
(8, 'Birth data from vital registration ', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 0, 'redundant with WB SCI variable?', 'United Nations Department of Economic and Social Affairs ', 'Whether the country has birth data from vital registration. ', '', 0, ''),
(9, 'Child immunization', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on child immunization, according to international standards. The proportion of one-year-old children immunized against measles is the proportion of children aged one who received one dose of measles vaccine. A child is considered adequately immunized against measles after receiving one dose of vaccine. Immunization is an essential component for reducing under-five mortality, and it serves as a proxy to measure the coverage and the quality of the child health care system. This indicator is also related to the fourth MDG aiming at reducing child mortality.', 'indicator (0 or 1)', 1, ''),
(10, 'Child malnutrition', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on child malnutrition, according to international standards. Prevalence of underweight children under-five years of age, also known as prevalence of child malnutrition (weight for age), is the percentage of children under-five whose weight for age is less than minus two standard deviations from the median for the international reference population ages 0 to 59 months. The data are based on the World Health Organization’s new child growth standards released in 2006. Child malnutrition is linked to poverty, low levels of education, and poor access to health services. Sufficient and good-quality nutrition is therefore critical for development, health, and survival of current and succeeding generations. This indicator monitors nutritional status and health in populations and relates to the first MDG aiming at reducing poverty and hunger.', 'indicator (0 to 1)', 1, ''),
(11, 'Child mortality', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on child mortality, according to international standards. Under-five mortality rate is the probability that a newborn baby will die before reaching age five, if subject to current age-specific mortality rates. The probability is expressed as a rate per 1,000. The indicator measures child survival. Survival of a child is closely linked to the provision of primary health-care services; but poverty, malnutrition, a decline in breast-feeding, maternal education, use of improved water, and inadequacy sanitation and health facilities are all associated with high child mortality. The indicator relates to the fourth MDG calling for reducing child mortality.', 'indicator (0 or 1)', 1, ''),
(12, 'Civil registration and vital statistics ', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 0, 'redundant with WB SCI variable', 'United Nations Statistics Division ', 'Existence of civil registration and vital statistics in the country. ', '', 0, ''),
(13, 'Civil society organizations active in statistics ', 'bar graph', 1, 0, 'Stakeholders'' interest', 'Production', 'Incentives', 'System', 1, '', 'UN ESANGO ', 'Whether civil society organisations are active in statistics of the country. ', 'quantity', 0, ''),
(14, 'Commitments to statistics ', 'bar graph', 1, 0, 'Budget', 'Investment', 'Resources', 'Organization', 0, 'drop this version of the statistic? was taken from the metabase', 'PARIS21 ', 'Financial support to development in statistics received by the country. ', '', 0, ''),
(15, 'Consumer price index base year', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Usage of CPI, according to international standards. Consumer Price Index (CPI) serves as indicators of inflation and reflects changes in the cost of acquiring a fixed basket of goods and services by the average consumer. Weights are usually derived from consumer expenditure surveys and the CPI base year refers to the year the weights were derived.', 'indicator (0 or 1)', 1, ''),
(16, 'Control of corruption', 'bar graph', 1, 0, 'Accountability', 'Planning', 'Politics and Power', 'System', 1, 'why include this in our dataset? Or why is this the only WGI that we would include in our dataset?', 'World Bank Governance Indicator (http://info.worldbank.org/governance/wgi)', 'World Bank Governance Indicator on Corruption. Control of corruption captures perceptions of the extent to which public power is exercised for private gain, including both petty and grand forms of corruption, as well as capture of the state by elites and private interests.', 'index (-3 to 3)', 0, ''),
(17, 'CountryStat', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'Subscription to CountryStat initiative', 'indicator (0 or 1)', 0, ''),
(18, 'CPI base year ', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 0, 'What does this tell us that the world bank sci binary indicator doesn''t?', 'World Bank Bulletin Board on Statistical Capacity ', 'The base year of the consumer price index. ', '', 0, ''),
(19, 'CRESS', 'binary', 1, 0, 'Funds infrastructure', 'Planning', 'Resources', 'System', 0, 'only 8 countries have this?', 'PARIS21', '', '', 0, ''),
(20, 'CRVS Coverage', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 0, 'redundant with the WB SCI variable', 'PARIS21', 'Coverage of births and deaths registration https://unstats.un.org/unsd/demographic-social/crvs/', '', 0, ''),
(21, 'Data dissemination policy', 'binary', 1, 1, 'Knowledge sharing', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'PARIS21', 'Existence of Microdata Access Policies', 'indicator (0 or 1)', 0, '1'),
(22, 'Data promotion events (MOW, user-producer dialogue) within the past 5 years', 'binary', 1, 0, 'Fundraising strategies', 'Dissemination', 'Management', 'Organization', 0, '', 'PARIS21', '', '', 0, ''),
(23, 'Details on budget ', 'binary', 1, 0, 'Budget', 'Investment', 'Resources', 'Organization', 1, '', 'PARIS21 ', 'Budget details of the NSO. ', 'indicator (0 or 1)', 0, ''),
(24, 'Details on legislation ', 'binary', 1, 0, 'Legislation, Principles and Institutional setting', 'Planning', 'Resources', 'System', 0, 'To be replaced by the SDG indicator has national statistical legislation that complies with the Fundamental Principles of Official Statistics', 'PARIS21 ', 'Statistical legislation details, link to statistical law, compliance with the UN principles, etc. ', '', 0, ''),
(25, 'Details on organization ', 'binary', 1, 0, 'Transparency', 'Planning', 'Politics and Power', 'Organization', 1, '', 'PARIS21 ', 'Detailed information on the national statistics office. ', 'indicator (0 or 1)', 0, ''),
(26, 'DevInfo/Country Info Portal', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, '', 'PARIS21', 'This indicator was intend to monitor data availability. DevInfo was promoted by the UN to do MDGs monitoring (http://www.devinfo.org/libraries/aspx/Home.aspx) but it’s not relevant anymore.', '', 0, ''),
(27, 'Downloadable reports from the website', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, '', 'PARIS21', '', '', 0, ''),
(28, 'Sectoral Statistical Strategy', 'binary', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 1, '', 'PARIS21', 'Existence of sectoral strategy for agriculture, education and other sectors, including in consultation with colleagues and online', 'indicator (0 or 1)', 0, ''),
(29, 'External debt reporting', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on external debt, according to international standards. The principal sources of external debt statistics are reports submitted to the World Bank through its Debtor Reporting System by reporting countries. Data quality and coverage vary among countries and from year to year. The reporting status shows, for the latest series, whether data were used as reported (actual), data were preliminary and included an element of staff estimation (preliminary), or data are staff estimates (estimate).', 'indicator (0 or 1)', 1, ''),
(30, 'Facebook', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, 'redundant with social media presence variable', 'PARIS21', 'The NSO uses facebook to disse;inate data and information', '', 0, ''),
(31, 'Fragile state ', 'binary', 0, 0, 'Legislation, Principles and Institutional setting', 'Production', 'Resources', 'System', 1, 'useful for country page?', 'World Bank (http://www.worldbank.org/en/topic/fragilityconflictviolence/brief/harmonized-list-of-fragile-situations)', 'Whether a country is on the World Bank''s Harmonized List of Fragile Situations. ', 'indicator (0 or 1)', 0, ''),
(32, 'GDDS subscription', 'binary', 1, 0, 'Quality assurance and codes of conduct', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'International Monetary Fund ', 'IMF members that participate in the e-GDDS agree to:\nCommit to using the e-GDDS as a framework for statistical development;\nDesignate a country coordinator; and\nPrepare descriptions of current statistical production and dissemination practices and plans for their improvement for posting on the DSBB.\nThe e-GDDS is designed to assist participants in improving data transparency and governance by publishing essential data for the analysis of macroeconomic conditions. It provides a framework for developing a clear roadmap to achieving higher data dissemination standards at a pace consistent with evolving statistical capacity. It focuses on publication of the data through a standardized platform to improve efficiency in data sharing, while identifying critical gaps to help prioritize technical assistance and donor support. Many countries are using participation in the e-GDDS as a step towards subscription to the SDDS.', 'indicator (0 or 1)', 0, ''),
(33, 'GDDS/SDDS', 'binary', 1, 0, 'Quality assurance and codes of conduct', 'Production', 'Skills & Knowledge', 'Organization', 0, 'redundant with separate GDDS and SDDS variables', 'PARIS21', 'Subscription to IMF SDDS/GDDS', '', 0, ''),
(34, 'GDP base year', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'what is this?', 'International Monetary Fund ', 'The baseline year of the gross domestic product indicator. ', '', 0, ''),
(35, 'GDP per capita', 'bar graph', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 1, 'useful for country page?', 'PARIS21 ', 'GDP per capita is the gross domestic product divided by population. ', 'constant USD', 1, ''),
(36, 'Gender equality in education', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on gender equality in education, acording to international standards. The indicator is defined as the ratio of the gross enrollment rate of girls to boys in primary and secondary education levels in both public and private schools. Women have an enormous impact on the well-being of their families and societies, but their potential is sometimes not realized because of discriminatory social norms, incentives, and legal institutions. Although their status has improved in recent decades, gender inequalities persist. Education is one of the most important aspects of human development, and eliminating gender disparity at all levels of education would help to increase the status and capabilities of women. This indicator provides a measure of equality of educational opportunity and relates to the third MDG that seeks to promote gender equality and the empowerment of women.', 'indicator (0 to 1)', 1, ''),
(37, 'Government effectiveness ', 'bar graph', 1, 0, 'Accountability', 'Planning', 'Politics and Power', 'System', 1, '', 'World Bank Governance Indicator (http://info.worldbank.org/governance/wgi)', 'Government effectiveness captures perceptions of the quality of public services, the quality of the civil service and the degree of its independence from political pressures, the quality of policy formulation and implementation, and the credibility of the government''s commitment to such policies. ', 'index (-3 to 3)', 1, ''),
(38, 'Government finance accounting concept', 'binary', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 1, '', 'World Bank Statistical Capacity Indicator', 'Quality of government finance accounting, according to international standards. Government finance accounting concept describes the accounting basis for reporting central government financial data. For many countries government finance data have been consolidated into one set of accounts capturing all the central government''s fiscal activities. Budgetary central government accounts do not necessarily include all central government units, the picture they provide of central government activities is usually incomplete.', 'indicator (0 or 1)', 1, ''),
(39, 'Government Statistical Capacity (Ibrahim)', 'bar graph', 1, 1, 'Legislation, Principles and Institutional setting', 'Planning', 'Resources', 'System', 1, '', 'Ibrahim Index of African Governance (http://iiag.online/)', 'This indicator assesses the capacity of statistical systems using a diagnostic framework which consists of three assessment areas: statistical methodology; source data; and periodicity and timeliness. It assesses the extent to which the Office of National Statistics produces detailed and timely data on employment and poverty. This includes whether data are available and disaggregated by sex, geographic region, age, and economic activity, whether recent surveys are available online for free or can be obtained on paper within less than two weeks at the cost of photocopying. It also assesses if the independence of the Office of National Statistics is guaranteed. It consists of two sub-indicators. (http://mo.ibrahim.foundation/iiag/methodology/)', 'index (0 to 100)', 1, ''),
(40, 'Health surveys', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of health surveys, according to international standards. Health surveys collect information on various aspects of health of populations, such as health expenditure, access, utilization, and outcomes. They typically include Demographic and Health Surveys, Core Welfare Indicator Questionnaire surveys, Multiple Indicator Cluster Survey, Integrated Surveys, Living Standard Measuring Surveys, Priority Surveys and other health related surveys. It is recommended that health surveys be conducted at least every 3 to 5 years.', 'indicator (0 to 1)', 1, ''),
(41, 'HIV/AIDS', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on HIV/AIDS prevalence, according to international standards. HIV prevalence at any given age is the difference between the cumulative numbers of people who have become affected with HIV up to this age and the number who died, expressed as a percentage of the total number alive at this age. The basis of measuring infection is the incidence of HIV among people aged 15-49. HIV/AIDS is one of the world’s most important killers and has its greatest impact on poor countries and poor people. This indicator relates to MDG number six to combat HIV/AIDS, malaria, and other diseases.', 'indicator (0 or 1)', 1, ''),
(42, 'IDA eligibility', 'binary', 0, 0, 'Legislation, Principles and Institutional setting', 'Investment', 'Resources', 'System', 1, 'useful for country page?', 'World Bank ', 'Whether the country is eligilbe for borrowing from the International Development Association. ', 'indicator (0 or 1)', 0, ''),
(43, 'IMF standards and codes reports', 'bar graph', 1, 0, 'Quality assurance and codes of conduct', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'International Monetary Fund ', 'IMF reports on the observance of standards and codes ', 'quantity', 0, ''),
(44, 'Import and export price indexes', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of import and export price indexes, according to international standards. Import and export price indexes measure changes in the price of goods and services in international trade. They are used to deflate the value of imports and exports. Import price index is also used as an indicator of future domestic inflation.', 'indicator (0 or 1)', 1, ''),
(45, 'Least developed country (LDC)', 'binary', 1, 0, 'Legislation, Principles and Institutional setting', 'Production', 'Resources', 'System', 1, 'useful for country page?', 'United Nations Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries and Small Island Developing States', 'Whether the country is a least developed country, defined by UNSD.', 'indicator (0 or 1)', 0, ''),
(46, 'Income poverty', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on income poverty, according to international standards. Proportion of population below US$1.25 a day is the percentage of the population living on less than $1.25 a day at 2005 international prices. The US$1.25 poverty line is compared to consumption or income per person and includes consumption from own production and income in kind. This poverty line has fixed purchasing power across countries. This indicator measures progress toward the reduction of extreme poverty and relates to the first MDG goal to eradicate extreme poverty and hunger.', 'indicator (0 to 1)', 1, ''),
(47, 'Industrial production index', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data for an industrial price index, according to international standards. Industrial production index measures changes in industrial production and is widely used for the observation and analysis of the current economic activity. Monthly survey on industrial production of index allows identifying the turning points in economic development at an early stage.', 'indicator (0 or 1)', 1, ''),
(48, 'Statistical society presence', 'binary', 1, 1, 'Legitimacy', 'Planning', 'Incentives', 'System', 1, '', 'International Statistics Institute (https://isi-web.org/index.php/resources/national-and-regional-statistical-societies)', 'Whether the International Statistical Institute (ISI) recognizes a non-governmental statistical body in the country. The ISI is a non-profit, non-government organization and has had consultative status with the Economic and Social Council of the United Nations since 1949.', 'indicator (0 or 1)', 0, '1'),
(49, 'Landlocked developing state ', 'binary', 0, 0, 'Legislation, Principles and Institutional setting', 'Production', 'Resources', 'System', 1, 'useful for country page?', 'United Nations Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries and Small Island Developing States', 'Whether the country is a landlocked developing state, defined by UNSD.', 'indicator (0 or 1)', 0, ''),
(50, 'Language accessibility ', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'The language accessibility of the NSO website. ', 'indicator (0 or 1)', 0, ''),
(51, 'Latest agricultural census ', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'The latest agricultural census. ', '', 0, ''),
(52, 'Latest household survey', 'text', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'The latest household survey. ', '', 0, ''),
(53, 'Latest industrial data ', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'The latest industrial data.', '', 0, ''),
(54, 'Latest population census ', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'The latest population census. ', '', 0, ''),
(55, 'Latest trade data ', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'The latest trade data. ', '', 0, ''),
(56, 'Latest water withdrawal data ', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'The latest wather withdrawal data. ', '', 0, ''),
(57, 'Maternal health', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on maternal health, according to international standards. Births attended by skilled health staff are the percentage of deliveries attended by personnel trained to give the necessary supervision, care, and advice to women during pregnancy, labor, and the postpartum period, to conduct deliveries on their own, and to care for the newborns. High maternal mortality rates in many countries are the result of inadequate reproductive health care for women and inadequately spaced births. The indicator monitors the ability of the health system to provide good antenatal and postnatal care for women and relates to the fifth MDG aiming at improving maternal health, with a target of reducing by three-quarters, between 1990 and 2015, the maternal mortality ratio.', 'indicator (0 to 1)', 1, ''),
(58, 'Metadata available on website ', 'binary', 1, 0, 'Transparency', 'Dissemination', 'Politics and Power', 'Organization', 1, '', 'PARIS21 ', 'The availability of metadata on the National Statistical Organization website. ', 'indicator (0 or 1)', 0, ''),
(59, 'Methodology assessment of statistical capacity (scale 0 - 100)', 'bar graph', 1, 0, 'Quality assurance and codes of conduct', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Quality of methodology (composite of indicators).', 'index (0 to 100)', 1, ''),
(60, 'Microdata ', 'binary', 1, 0, 'Existing data', 'Dissemination', 'Resources', 'System', 0, 'Duplicated with #6', 'PARIS21', '', '', 0, ''),
(61, 'NADA (National Data Archive)', 'binary', 1, 1, 'Relationship with users', 'Dissemination', 'Politics and Power', 'System', 1, '', 'NADA (http://www.ihsn.org/nada)', 'Usage of NADA statistical tool for microdata cataloging', 'indicator (0 or 1)', 0, ''),
(62, 'National accounts base year', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Quality of national accounts, according to international standards. National accounts base year is the year used as the base period for constant price calculations in the country''s national accounts. It is recommended that he base year of constant price estimates be changed periodically to reflect changes in economic structure and relative prices.', 'indicator (0 or 1)', 1, ''),
(63, 'Data portal', 'binary', 1, 0, 'Relationship with users', 'Dissemination', 'Politics and Power', 'System', 1, '', 'PARIS21', 'The existence of a national database or data portal. ', 'indicator (0 or 1)', 0, ''),
(64, 'National immunization coverage', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on national imunization coverage, according to international standards. WHO and UNICEF collect and review data available on national immunization coverage. Then estimates on the level of immunization coverage are made by using officially reported data, survey results, scientific literature, and by taking account of potential biases and consultation with local experts. The gap between the international estimates and the government official estimates therefore suggests that the estimation method adopted by the country differs from the internationally recommended practice.', 'indicator (0 or 1)', 1, ''),
(65, 'National Strategy for Development of Statistics', 'binary', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, 'Duplicated with the SDG indicator. ', 'PARIS21', 'The existence of a National Strategy on Development of Statistics. ', '', 0, ''),
(66, 'Data portal', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, '', 'PARIS21', 'Existence of national data base, whether or not maintained by the country', '', 0, ''),
(67, 'National Statistical Council', 'binary', 1, 0, 'Legislation, Principles and Institutional setting', 'Planning', 'Resources', 'System', 1, '', 'PARIS21', 'Existence of an agency/board/institution that advises the Chief Statistician on National Statistical Organization activities, primarily on program priorities. The name varies across countries: National Statistical Board, National Statistical Commission, National Statistical Committee.', 'indicator (0 or 1)', 0, ''),
(68, 'National support to Statistics > 50%', 'binary', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, '', 'PARIS21', 'Whether the share of national statistical budget dedicated to statistics exceeds 50 percent', 'indicator (0 or 1)', 0, ''),
(69, 'Newsletter', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, 'is this useful? Can it be folded into some other indicator about dissemination?', 'PARIS21', '', '', 0, ''),
(70, 'NSDS existing ', 'ordinal', 1, 1, 'Plans', 'Planning', 'Resources', 'System', 0, 'To be replaced by the SDG indicator Country has a national statistical plan that is fully funded and under implementation', 'PARIS21', 'The existence of a national strategy for the development in statistics. ', '', 0, ''),
(71, 'NSDS name ', 'text', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, 'useful for country page?', 'PARIS21', 'The name of the national strategy for the development of statistics. ', '', 0, ''),
(72, 'NSDS next ', 'ordinal', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, '?', 'PARIS21', 'The name of the next national strategy for the development of statistics. ', '', 0, ''),
(73, 'NSDS time span existing ', 'ordinal', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, '?', 'PARIS21', 'The timespan for the current national strategy for the development of statistics.', '', 0, ''),
(74, 'NSDS time span next ', 'ordinal', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, '?', 'PARIS21', 'The timespan for the next nationl strategy for the development of statistics. ', '', 0, ''),
(75, 'National statistical strategy generation', 'binary', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 1, '', 'PARIS21', 'The generation of the current national statistical strategy.', 'indicator (0 or 1)', 0, ''),
(76, 'National statistical plan', 'binary', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 1, '', 'PARIS21', 'Existence of a National Strategy for Development of Statistics or a National Statistical Plan', 'indicator (0 or 1)', 0, ''),
(77, 'NSO website URL ', 'text', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, 'useful for country page?', 'PARIS21', 'Link of the NSO website', 'link', 0, ''),
(78, 'ODIN overall data coverage score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score of data coverage. Data coverage is assessed against five elements of coverage.\nCoverage Element 1: Indicator Coverage and Disaggregation\nCoverage Element 2: Data Availability for Last 5 Years\nCoverage Element 3: Data Availability for Last 10 Years\nCoverage Element 4: First Administrative Level\nCoverage Element 5: Second Administrative Level', 'index (0 to 100)', 1, ''),
(79, 'ODIN economic data coverage score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on coverage of economic statistics data.', 'index (0 to 100)', 1, ''),
(80, 'ODIN economic data openness score', 'bar graph', 1, 0, 'Accountability', 'Dissemination', 'Politics and Power', 'System', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on openness of economic statistics data.', 'index (0 to 100)', 1, ''),
(81, 'ODIN overall economic data score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on economic statistics. Economic Statistics include:\n10. National Accounts\n11. Labor Statistics\n12. Price Indexes\n13. Government Finance\n14. Money and Banking\n15. International Trade\n16. Balance of Payments ', 'index (0 to 100)', 1, ''),
(82, 'ODIN environmental data coverage score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on coverage of environmental statistics data.', 'index (0 to 100)', 1, ''),
(83, 'ODIN environmental data openness score', 'bar graph', 1, 0, 'Accountability', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on openness of environmental statistics data.', 'index (0 to 100)', 1, ''),
(84, 'ODIN overall environmental data score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on environmental statistics. Environmental Statistics include:\n17. Land Use\n18. Resource Use\n19. Energy Use\n20. Pollution\n21. Built Environment', 'index (0 to 100)', 1, ''),
(85, 'ODIN overall data openness score', 'bar graph', 1, 0, 'Accountability', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score of data openness. Data openness is assessed against five elements of openness.\nOpenness Element 1: Machine Readability\nOpenness Element 2: Non-proprietary Format\nOpenness Element 3: Download Options\nOpenness Element 4: Metadata Availability\nOpenness Element 5: Free/Unrestricted Terms of Use', 'index (0 to 100)', 1, ''),
(86, 'ODIN overall data coverage and openness score', 'bar graph', 1, 1, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN scores are summarized along both dimensions of the ODIN assessment: by categories, and by elements. Categories: social statistics, economic statistics, and environmental statistics. Elements: coverage and openness. ', 'index (0 to 100)', 1, '1'),
(87, 'ODIN social data coverage score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on coverage of social statistics data.', 'index (0 to 100)', 1, ''),
(88, 'ODIN social data openness score', 'bar graph', 1, 0, 'Accountability', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on openness of social statistics data.', 'index (0 to 100)', 1, ''),
(89, 'ODIN overall social data score', 'bar graph', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'Open Data Watch (http://odin.opendatawatch.com/)', 'ODIN score on social statistics. Social Statistics include:\n1. Population and Vital Statistics\n2. Education Facilities\n3. Education Outcomes\n4. Health Facilities\n5. Health Outcomes\n6. Reproductive Health\n7. Gender Statistics\n8. Crime and Justice Statistics\n9. Poverty Statistics ', 'index (0 to 100)', 1, ''),
(90, 'Online data accessibility ', 'binary', 1, 0, 'Accountability', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'PARIS21 ', 'The accessibility of online data. ', 'indicator (0 or 1)', 0, ''),
(91, 'Open Government', 'binary', 1, 0, 'Accountability', 'Dissemination', 'Politics and Power', 'System', 1, 'different values in metabase vs. prioritization tool', 'OGP (https://www.opengovpartnership.org/participants)', 'Whether the country participates in the Open Government Partnership', 'indicator (0 or 1)', 1, ''),
(92, 'Per capita GDP growth', 'ordinal', 1, 0, 'Existing data', 'Production', 'Skills & Knowledge', 'System', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on per capita GDP growth, according to international standards. GDP per capita is the sum of gross value added by all resident producers in the economy plus any product taxes (less subsidies) not included in the valuation of output, divided by mid-year population. Growth is calculated from constant price GDP data in local currency. Sustained economic growth increases average incomes and is strongly linked to poverty reduction. GDP per capita provides a basic measure of the value of output per person, which is an indirect indicator of per capita income. Growth in GDP and GDP per capita are considered broad measures of economic growth.', 'indicator (0 to 1)', 1, ''),
(93, 'Periodicity and timeliness assessment of statistical capacity (scale 0 - 100)', 'bar graph', 1, 0, 'Quality assurance and codes of conduct', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Quality of statistical production periodicity (composite of indicators).', 'index (0 to 100)', 1, ''),
(94, 'Population', 'bar graph', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 1, 'useful for country page?', 'PARIS21 ', 'Total number of people living in the country. ', 'people', 1, ''),
(95, 'Population census', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of a population census according to international standards. Population censuses collect data on the size, distribution and composition of population and information on a broad range of social and economic characteristics of the population. It also provides sampling frames for household and other surveys. It is recommended that population censuses be conducted at least every 10 years.', 'indicator (0 or 1)', 1, ''),
(96, 'Poverty surveys', 'ordinal', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of povery surveys according to international standards. Poverty surveys collect data on household income, consumption and expenditure, including income in kind. They typically include income, expenditure, and consumption surveys, household budget surveys, Integrated Surveys, Living Standard Measuring Surveys, and other poverty related surveys. It is recommended that poverty surveys be conducted at least every 3 to 5 years.', 'indicator (0 to 1)', 1, ''),
(97, 'Press releases ', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, 'redundant', 'PARIS21 ', 'The recent press release from the national statitics office. ', '', 0, ''),
(98, 'Press releases issued at least quarterly', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, 'fold into another dissemination variable?', 'PARIS21', 'Timeliness and frequency of official statements issued to journalists on statistical indicators', 'indicator (0 or 1)', 0, ''),
(99, 'Primary completion', 'ordinal', 1, 0, 'Existing data', 'Production', 'Resources', 'System', 1, '', 'World Bank Statistical Capacity Indicator', 'Existence of data on primary education completion, according to international standards. Primary completion rate (PCR) is the number of students successfully completing the last year of (or graduating from) primary school in a given year, divided by the number of children of official graduation age in the population. Because of difficulties with developing data based on this definition, data analysis is generally based on the PCR proxy indicator which is the number of children reaching the last year of primary school (as defined by a country) net of repeaters. The indicator, which monitors education system coverage and student progression, is intended to measure human capital formation and school system quality and efficiency and relates to the second MDG to achieve universal primary education.', 'indicator (0 to 1)', 1, ''),
(100, 'Processing-friendly data format', 'binary', 1, 0, 'Relationship with users', 'Dissemination', 'Politics and Power', 'System', 1, '', 'PARIS21 ', 'The data format is processing-friendly if it is published in digital formats such as .csv and .xls/.xlsx instead of formats such as .doc or .pdf. ', 'indicator (0 or 1)', 0, ''),
(101, 'National Development Plan timespan', 'ordinal', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, '?', 'PARIS21', 'The timespan for the Poverty Reduction Strategy Paper or the national development plan. ', '', 0, ''),
(102, 'Regulatory quality ', 'bar graph', 1, 0, 'Accountability', 'Planning', 'Politics and Power', 'System', 1, '', 'World Bank Governance Indicator (http://info.worldbank.org/governance/wgi)', 'Regulatory quality captures perceptions of the ability of the government to formulate and implement sound policies and regulations that permit and promote private sector development.', 'index (-3 to 3)', 0, ''),
(103, 'Rule of law ', 'bar graph', 1, 0, 'Legislation, Principles and Institutional setting', 'Planning', 'Resources', 'System', 1, '', 'World Bank Governance Indicator (http://info.worldbank.org/governance/wgi)', 'Rule of law captures perceptions of the extent to which agents have confidence in and abide by the rules of society, and in particular the quality of contract enforcement, property rights, the police, and the courts, as well as the likelihood of crime and violence', 'index (-3 to 3)', 0, ''),
(104, 'SDDS subscription ', 'binary', 1, 1, 'Quality assurance and codes of conduct', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'International Monetary Fund ', 'The SDDS is a global benchmark for disseminating macroeconomic statistics to the public. SDDS subscription indicates that a country meets the test of “good statistical citizenship.” The SDDS Guide for Subscribers and Users contains details on commitments undertaken by a subscriber, and is available on the DSBB. Countries that subscribe to the SDDS agree to follow good practices in four areas: the coverage, periodicity, and timeliness of data; public access to those data; data integrity; and data quality.\nSubscribing countries commit to:\nDisseminate the data required by the SDDS punctually and with the prescribed periodicity and timeliness on a national webpage, the National Summary Data Page (NSDP), which is hyperlinked to the DSBB. A complete list of NSDPs can be accessed by clicking here.\nProvide to the IMF an advance release calendar (ARC) containing release dates for the current month and at least the following three months for each prescribed category of data for posting on the DSBB.\nProvide detailed information about their statistical practices, or metadata, for dissemination on the DSBB. The metadata follow the rigorous format of the Data Quality Assessment Framework (DQAF). The DQAF was developed by the IMF to assess the quality of countries’ economic and financial data. Details about DQAF are available on the Data Quality Reference Site.\nCertify the accuracy of the metadata on an annual basis.\nUse standardized electronic reporting procedures to monitor more effectively their observance of the SDDS is also a required undertaking for SDDS subscribers.', 'indicator (0 or 1)', 0, '1'),
(105, 'Share of foreign support dedicated to demographic and social statistics (ten years)', 'bar graph', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, '', 'PARIS21 ', 'Share of foreign support dedicated to demographic and social statistics', 'percentage', 0, ''),
(106, 'Share of foreign support dedicated to economic statistics (ten years)', 'bar graph', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, '', 'PARIS21 ', 'Share of foreign support dedicated to economic statistics.', 'percentage', 0, ''),
(107, 'Share of foreign support dedicated to environmental and multi-sectoral statistics (ten years)', 'bar graph', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, '', 'PARIS21 ', 'Share of foreign support dedicated to environmental and multisectoral statistics. ', 'percentage', 0, ''),
(108, 'Share of foreign support dedicated to general data collection, preservation and dissemination (ten years)', 'bar graph', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, '', 'PARIS21 ', 'Share of foreign support dedicated to general data collection, preservation and dissemination.', 'percentage', 0, ''),
(109, 'Small island developing state (SIDS)', 'binary', 0, 0, 'Funds infrastructure', 'Production', 'Resources', 'System', 1, 'useful for country page?', 'United Nations Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries and Small Island Developing States', 'Whether the country is a small island developing state, defined by UNSD.', 'indicator (0 or 1)', 0, ''),
(110, 'Social media', 'binary', 1, 0, 'Advocacy strategy', 'Dissemination', 'Management', 'System', 1, 'improves on/supersedes the pure facebook indicator', 'PARIS21', 'Whether the National Statistical Organization uses social media (Facebook and/or Twitter) to disseminate data and information', 'indicator (0 or 1)', 0, ''),
(111, 'Source data assessment of statistical capacity (scale 0 - 100)', 'bar graph', 1, 0, 'Quality assurance and codes of conduct', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Quality of source data (composite of indicators).', 'index (0 to 100)', 1, ''),
(112, 'Special Data Dissemination Standard', 'binary', 1, 0, 'Accountability', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'World Bank Statistical Capacity Indicator', 'Use of the Special Data Dissemination Standard. The Special Data Dissemination Standard (SDDS) was established by the IMF for member countries that have or that might seek access to international capital markets, to guide them in providing their economic and financial data to the public. Although subscription is voluntary, the subscribing member needs to be committed to observing the standard and provide information about its data and data dissemination practices (metadata). The metadata are posted on the IMF''s Dissemination Standards Bulletin Board. The SDDS is expected to enhance the availability of timely and comprehensive data and improve the functioning of financial markets.', 'indicator (0 or 1)', 1, ''),
(113, 'Statistical Capacity Indicator (World Bank, overall score)', 'bar graph', 1, 1, 'Legislation, Principles and Institutional setting', 'Use', 'Resources', 'System', 1, '', 'World Bank Statistical Capacity Indicator', 'The Statistical Capacity Indicator provides an overview of the capacity of a country''s national statistical system based on a diagnostic framework thereby assessing three dimensions: Methodology, Source Data, and Periodicity and Timeliness.', 'quantity score', 1, '1'),
(114, 'Statistical Literacy Indicator', 'bar graph', 1, 0, 'Data Literacy', 'Use', 'Skills & Knowledge', 'System', 0, 'includes many not available', 'PARIS21', 'The overalll score of the statistical literacy indicator. ', '', 0, ''),
(115, 'Statistical Literacy Indicator (level 1)', 'bar graph', 1, 1, 'Legislation, Principles and Institutional setting', 'Use', 'Resources', 'System', 1, '', 'PARIS21', 'The score of level 1 sub-index of the statistical literacy indicator. ', 'quantity score', 0, '1'),
(116, 'Statistical Literacy Indicator (level 2)', 'bar graph', 1, 1, 'Legislation, Principles and Institutional setting', 'Use', 'Resources', 'System', 1, '', 'PARIS21', 'The score of level 2 sub-index of the statistical literacy indicator.', 'quantity score', 0, ''),
(117, 'Statistical Literacy Indicator (level 3)', 'bar graph', 1, 1, 'Legislation, Principles and Institutional setting', 'Use', 'Resources', 'System', 1, '', 'PARIS21', 'The score of level 3 sub-index of the statistical literacy indicator.', 'quantity score', 0, ''),
(118, 'Statistical Law / Act', 'binary', 1, 0, 'Legislation, Principles and Institutional setting', 'Planning', 'Resources', 'System', 0, '', 'PARIS21', 'The Statistics Act gives the NSO the authority to collect, compile, analyze, abstract, and publish information on the economic, social and general conditions of the country and its citizens on bhalf of the National government', '', 0, ''),
(119, 'System of National Accounts ', 'ordinal', 1, 0, 'Infrastructure', 'Planning', 'Resources', 'Organization', 0, 'redundant with WB SCI variable', 'PARIS21 ', 'Existence of system of national accounts. ', '', 0, ''),
(120, 'NSDS existing', 'binary', 1, 0, 'Plans', 'Planning', 'Resources', 'System', 0, 'duplicated with 70', 'PARIS21', 'The existence of a National Strategy on Development of Statistics. ', '', 0, ''),
(121, 'Total commitments (annual)', 'bar graph', 1, 1, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, 'some are blank/empty', 'PARIS21 ', 'Total support to development in statistics received each year (in current price). ', 'constant USD', 1, '1');
INSERT INTO `indicators_new3` (`id`, `name`, `dataviz_type`, `direction`, `key_indicator`, `family`, `classif`, `area`, `level`, `final_list`, `note`, `source`, `definition`, `tag`, `timeseries`, `default_cpage`) VALUES
(122, 'Total commitments (ten years)', 'bar graph', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 0, 'includes some blank years? Would need to do an average…', 'PARIS21 ', 'Total support to development in statistics received in past 10 years (in current price). ', '', 1, ''),
(123, 'Total commitments (three years)', 'bar graph', 1, 0, 'Funds infrastructure', 'Investment', 'Resources', 'System', 0, 'includes some blank years? Would need to do an average…', 'PARIS21 ', 'Total support to development in statistics received in past 3 years (in current price). ', '', 1, ''),
(124, 'Twitter', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, 'redundant with social media presence variable', 'PARIS21', '', '', 0, ''),
(125, 'Enrollment reporting to UNESCO', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Reporting of education data to UNESCO. UNESCO Institute of Statistics compiles data on education based on official responses to surveys and from reports provided by education authorities in each country. As the recommended periodicity of these data is annual, annual reporting from countries is considered a good practice.', 'indicator (0 or 1)', 1, ''),
(126, 'UN Fundamentals Principles of Statistics compliance', 'binary', 1, 0, 'Quality assurance and codes of conduct', 'Planning', 'Resources', 'System', 0, 'redundant after the official data from Yu', 'PARIS21', 'Whether the national statistical law is compliant with the UN Fundamentals Principles of Statistics (or updated after 2009, when the African Charter on Statistics was adopted)', '', 0, ''),
(127, 'Use of Statistics Indicator', 'bar graph', 1, 1, 'Accountability', 'Use', 'Politics and Power', 'System', 1, 'better for 2018 from PRESS than 2017 from metabase?', 'PARIS21 ', 'The composite indicator in reference to statistical terms and indicators in national policy documents. The sub-index of this indicator includes the level of complexity, disaggregation, sector distribution, and monitoring and evaluation framework. ', 'quantity score', 1, '1'),
(128, 'Regional data platform', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'Whether the country''s National Statistical Organization uses a regional data dissemination platform', 'indicator (0 or 1)', 0, ''),
(129, 'User contact ', 'binary', 1, 0, 'Relationship with users', 'Dissemination', 'Politics and Power', 'System', 1, '', 'PARIS21 ', 'The existence of user contact. ', 'indicator (0 or 1)', 0, ''),
(130, 'User-tailored services ', 'binary', 1, 0, 'Relationship with users', 'Dissemination', 'Politics and Power', 'System', 1, '', 'PARIS21 ', 'The existence of user tailored services.', 'indicator (0 or 1)', 0, ''),
(131, 'Vital registration', 'binary', 1, 0, 'Statistical production processes', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank Statistical Capacity Indicator', 'Quality of vital registration data and system coverage. Vital registration systems record the occurrence and characteristics of vital events pertaining to the population and serve as a main source of vital statistics. Countries with complete vital statistics registries may have more accurate and timely demographic indicators.', 'indicator (0 or 1)', 1, ''),
(132, 'Website', 'binary', 1, 0, 'Advocacy strategy', 'Dissemination', 'Skills & Knowledge', 'System', 1, 'link this to the url, would be useful for the country page', 'PARIS21', 'Website link to the National Statistical Organization', 'indicator (0 or 1)', 0, ''),
(133, 'Website updates ', 'binary', 1, 0, 'Advocacy strategy', 'Dissemination', 'Skills & Knowledge', 'System', 1, '', 'PARIS21 ', 'The frequency of updates of the website in terms of news and statistical releases, data availability.  ', 'indicator (0 or 1)', 0, ''),
(134, 'Website and Social Media Updated Regularly', 'binary', 1, 0, 'Communication', 'Dissemination', 'Skills & Knowledge', 'Organization', 0, '', 'PARIS21', 'Timeliness and frequency of updates to website and social media contents', '', 0, ''),
(135, 'UN FPOS', 'binary', 1, 1, 'Quality assurance and codes of conduct', 'Planning', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'Whether the national statistical legislation complies with United Nations Fundamental Principles of Statistics (SDG 17.18.2)', 'indicator (0 or 1)', 0, ''),
(136, 'Statistical plan implemented', 'binary', 1, 1, 'Plans', 'Planning', 'Resources', 'System', 1, '', 'PARIS21', 'Whether there is a national statistical plan under implementation (SDG 17.18.3)', 'indicator (0 or 1)', 0, '1'),
(137, 'National statistical plan under implementation and fully funded (SDG 17.18.3)', 'binary', 1, 0, 'Plans', 'Investment', 'Resources', 'System', 0, 'redundant with the following one (there are no fully funded plans that are not under implementation, so to say fully funded is to say fully funded and under implementation)--unless we were to mark as zero (i.e., not fully funded) the ones that are not implemented, as well)', 'PARIS21', 'Whether the national statistical plan under implementation is fully funded (SDG 17.18.3)', '', 0, ''),
(138, 'Statistical plan fully funded', 'binary', 1, 1, 'Funds infrastructure', 'Investment', 'Resources', 'System', 1, '', 'PARIS21', 'Whether the national statistical plan under implementation is fully funded (SDG 17.18.3)', 'indicator (0 or 1)', 0, '1'),
(139, 'Microdata datasets online', 'bar graph', 1, 0, 'Statistical production processes', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'World Bank (http://microdata.worldbank.org/index.php/catalog)', 'The number of datasets that are available through the World Bank microdata cataloging tool', 'quantity', 0, ''),
(140, 'Microdata dataset citations', 'bar graph', 1, 0, 'Stakeholders'' interest', 'Use', 'Incentives', 'System', 1, '', 'World Bank (http://microdata.worldbank.org/index.php/catalog)', 'The number of citations in peer-reviewed international journals, from the datasets that are available through the World Bank microdata cataloging tool', 'quantity', 0, ''),
(141, 'Microdata average citations per dataset', 'bar graph', 1, 0, 'Stakeholders'' interest', 'Use', 'Incentives', 'System', 1, '', 'World Bank (http://microdata.worldbank.org/index.php/catalog)', 'The average number of citations in peer-reviewed international journals, per dataset, from the datasets that are available through the World Bank microdata cataloging tool', 'quantity', 0, ''),
(142, 'Tenure as NSO head', 'text', 0, 0, 'Professional background', 'Use', 'Resources', 'Individual', 1, '', 'PARIS21', 'The ratio of the number of years in power of the current head of the National Statistical Organization, against the current head of state.', 'ratio of years in office (NSO state : head of state)', 0, ''),
(143, 'SDG portal', 'binary', 1, 1, 'Advocacy strategy', 'Planning', 'Skills & Knowledge', 'System', 1, '', 'PARIS21', 'Existence of official country-operated, dedicated online portal for reporting SDG progress', 'indicator (0 or 1)', 0, ''),
(144, 'Online appendices', 'binary', 1, 0, 'Quality assurance and codes of conduct', 'Dissemination', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'Whether explanatory material accompanies online published data (e.g., erratum, methodology, metadata, guides, manuals)', 'indicator (0 or 1)', 0, ''),
(145, 'Metadata published', 'binary', 1, 0, 'Existing data', 'Dissemination', 'Resources', 'System', 1, '', 'PARIS21', 'More than 50% of data published includes metadata', 'indicator (0 or 1)', 0, ''),
(146, 'International data dissemination', 'binary', 1, 0, 'Accountability', 'Dissemination', 'Politics and Power', 'System', 1, '', 'PARIS21', 'Use of international data dissemination platform (e.g., African Information Highway, CountryStat, DevInfo, Eurostat, IMIS, NADA, OECDStat, Prognoz)', 'indicator (0 or 1)', 0, ''),
(147, 'Quality management', 'binary', 1, 1, 'Quality assurance and codes of conduct', 'Production', 'Skills & Knowledge', 'Organization', 1, '', 'PARIS21', 'Follow international quality management framework (e.g., GDDS, DQAF, Total Quality Management, ISO EN 9001)', 'indicator (0 or 1)', 0, '1'),
(148, 'Regulations available online', 'binary', 1, 0, 'Legislation, Principles and Institutional setting', 'Planning', 'Resources', 'System', 1, '', 'PARIS21', 'Whether the National Statistical Organization regulations are published online', 'indicator (0 or 1)', 0, ''),
(149, 'SDMX', 'binary', 1, 0, 'Legislation, Principles and Institutional setting', 'Dissemination', 'Resources', 'System', 1, '', 'PARIS21', 'Use of the Statistical Data and Metadata eXchange, SDMX, at least in some statistical domains or for some datasets', 'indicator (0 or 1)', 0, ''),
(150, 'Income group (World Bank)', 'text', 0, 0, 'Legislation, Principles and Institutional setting', 'Production', 'Resources', 'System', 1, '', 'World Bank (https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups)', 'World Bank Country and Lending Groups', 'class', 0, '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
